# =========================
# Ruff
# =====
[tool.ruff]
target-version = "py38"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D104",  # undocumented-public-package
    "D100",  # undocumented-public-module
    "D101",  # undocumented-public-class
    "D106",  # undocumented-public-nested-class
    "D107",  # undocumented-public-init
    "D102",  # undocumented-public-method
    "D105",  # undocumented-magic-method
    "D103",  # undocumented-public-function
    "D203",  # one-blank-line-before-class (conflict with D211)
    "D213",  # multi-line-summary-second-line (conflict with D212)
    "ANN401",  # any-type
    "ANN101",  # missing-type-self
    "ANN102",  # missing-type-cls
    "FIX002",  # line-contains-todo
    "TD003",  # missing-todo-link
    "S311",  # suspicious-non-cryptographic-random-usage
    "G004",  # logging-f-string
    "S106",  # hardcoded-password-func-arg
    "S608",  # hardcoded-sql-expression
    "TRY003",  # raise-vanilla-args
    "TRY400",  # error-instead-of-exception
    "PLE1205",  # logging-too-many-args
    "TCH001",  # typing-only-first-party-import
    "FBT001",  # boolean-type-hint-positional-argument
    "FBT002",  # boolean-default-value-positional-argument

    "ANN201",  # missing-return-type-undocumented-public-function
    "ANN001",  # missing-type-function-argument

    "COM812",  # missing-trailing-comma (Suggested by ruff to disable)
    "ISC001",  # single-line-implicit-string-concatenation (Suggested by ruff to disable)
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
combine-as-imports = true

[tool.ruff.format]
skip-magic-trailing-comma = true

# =========================
# Pylint
# =====
[tool.pylint.main]
py-version = "3.8"
ignore-patterns = [
    "\\d{4}_.*?.py"  # ignore django migrations
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint."messages control"]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "import-error",
    "duplicate-code",
    "too-few-public-methods",
    "fixme",  # Ruff will handle it
    "broad-exception-raised",  # Ruff will handle it
    "line-too-long",  # Ruff will handle it
    "unused-argument",  # Ruff will handle it
    "too-many-arguments",  # Ruff will handle it
    "too-many-branches",  # Ruff will handle it
    "too-many-statements",  # Ruff will handle it
    "bare-except",  # Ruff will handle it
]
