# Generated by Django 4.1.4 on 2023-01-02 11:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                (
                    'action',
                    models.CharField(
                        choices=[('FO', 'Forget'), ('RE', 'Register'), ('IN', 'Invite'), ('EM', 'Email Change')],
                        max_length=2,
                        verbose_name='Action',
                    ),
                ),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_for', models.CharField(choices=[('EM', 'Email')], max_length=2, verbose_name='Is For')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('additional_data', models.TextField(blank=True, null=True, verbose_name='Additional Data')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'ordering': ('-create_time',),
                'get_latest_by': ('create_time',),
                'abstract': False,
            },
        )
    ]
