# Generated by Django 4.1.4 on 2023-01-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('notification_helper', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecipientlog',
            options={
                'get_latest_by': ('create_time',),
                'ordering': ('-create_time',),
                'verbose_name': 'Email Recipient Log',
                'verbose_name_plural': 'Email Recipient Logs',
            },
        )
    ]
